### ISSUE TITLE
Plotting colour by region (i.e. colour fill regions based on values in input file)  

### ISSUE THREAD

**Issue by ajaynairdev** [ishraqn/CGC-DataVizTool#15]

**Comment by loganDoran** [comment]
**Description**: 
Generate colour gradients based on the range and distribution of data values for colour filling regions based on values in the input file.

**Tasks**:
- [ ] Develop algorithms to generate colour gradients based on data range and distribution.
- [ ] Implement colour filling functionality for regions based on values in the input file.

**Acceptance Criteria**:
- The application accurately generates colour gradients based on data values.
- Regions are filled with colours corresponding to the values in the input file.
